package sec1;

public class ExceptionExam2 {
	public static void main(String[] args) {
		String name = null;
		//실제 처리할 문장(try)이 예외가 발생하면, 예외 처리 문장(catch)을 실행
		try {
			//실제 처리할 문장
			System.out.println(name.toString());		
		} catch(NullPointerException e) {
			e.printStackTrace();
		} catch(Exception e) {
			System.out.println("알 수 없는 예외가 발생하였습니다.");
		}
	}
}
